I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    init -1 python:
  File "game/script.rpy", line 31, in <module>
    update_stat_labels()
NameError: name 'update_stat_labels' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    init -1 python:
  File "/home/yallicol/renpy-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/yallicol/renpy-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 31, in <module>
    update_stat_labels()
NameError: name 'update_stat_labels' is not defined

Linux-6.8.9-100.fc38.x86_64-x86_64-with-glibc2.37 x86_64
Ren'Py 8.3.4.24120703
src 1.0
Fri Feb 14 15:40:02 2025
